# Generated by Django 4.0.3 on 2022-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_projeto', models.CharField(max_length=300)),
                ('data_pub', models.DateField()),
                ('resumo_projeto', models.TextField()),
                ('linguagem_projeto', models.CharField(max_length=100)),
                ('framework_projeto', models.CharField(max_length=100)),
                ('logo_projeto', models.CharField(max_length=50)),
                ('banco_projeto', models.CharField(max_length=100)),
                ('texto1_projeto', models.TextField()),
                ('texto2_projeto', models.TextField()),
                ('link_projeto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
                ('link_linkedin', models.CharField(max_length=500)),
            ],
        ),
    ]
